version: '3.8'

# Stack Simplificada de Observabilidade
# Foco: Logs de Aplicação + Monitoramento de Banco de Dados
#
# Endpoints:
# - Grafana: http://localhost:33000 (admin / sua_senha_do_env)
# - PMM Server: http://localhost:33443 (admin / admin)
# - OTLP HTTP: http://localhost:34318 (para enviar logs da aplicação)

networks:
  observability:
    driver: bridge
    name: observability

volumes:
  grafana_data:
  loki_data:
  pmm_data:

services:
  # GRAFANA - Visualização de Dados
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-11.2.0}
    container_name: grafana
    restart: unless-stopped
    ports:
      - "33000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - observability
    depends_on:
      - loki

  # LOKI - Armazenamento de Logs
  loki:
    image: grafana/loki:${LOKI_VERSION:-2.9.2}
    container_name: loki
    restart: unless-stopped
    ports:
      - "33100:3100"
    volumes:
      - loki_data:/loki
      - ./configs/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  # OPENTELEMETRY COLLECTOR - Recebe logs da aplicação
  otel-collector:
    image: otel/opentelemetry-collector-contrib:${OTEL_COLLECTOR_VERSION:-0.88.0}
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - "34318:4318"  # OTLP HTTP (usa este na sua aplicação)
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - observability
    depends_on:
      - loki

  # PMM SERVER - Monitoramento de Banco de Dados
  pmm-server:
    image: percona/pmm-server:${PMM_SERVER_VERSION:-2.40.1}
    container_name: pmm-server
    restart: unless-stopped
    ports:
      - "33443:80"    # Interface Web do PMM
      - "34443:443"   # HTTPS
    volumes:
      - pmm_data:/srv
    environment:
      - PMM_ADMIN_PASSWORD=${PMM_ADMIN_PASSWORD:-admin}
    networks:
      - observability
