# Configuração de Data Sources do Grafana
apiVersion: 1

datasources:
  # Data Source do Loki - Logs da Aplicação
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
