# Configuração Simplificada do OpenTelemetry Collector
# Foco: Receber logs da aplicação e enviar para o Loki

receivers:
  # Recebe logs via OTLP HTTP (porta 4318)
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Agrupa logs em batches antes de enviar
  batch:
    timeout: 5s
    send_batch_size: 100

  # Adiciona atributos úteis aos logs
  resource:
    attributes:
      - key: service.environment
        value: production
        action: insert

exporters:
  # Envia logs para o Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "service_name"
        service.environment: "service_environment"
      attributes:
        level: "level"

  # Exibe logs no console (útil para debug)
  logging:
    loglevel: info

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [loki, logging]
